require "mini.extra".setup()
-- require "mini.pick".setup()
require "mini.ai".setup()
require "mini.align".setup()
require "mini.move".setup()
require "mini.pairs".setup()
require "mini.surround".setup()
require "mini.basics".setup()
require "mini.diff".setup()
-- require "mini.indentscope".setup()
-- require "mini.git".setup()
-- require "mini.jump".setup()
-- require "mini.jump2d".setup()
-- require "mini.icons".setup()
-- require "mini.statusline".setup()
-- require "mini.tabline".setup()
require "mini.files".setup()
