return {
  {
    "williamboman/mason.nvim",
    opts = {
      ensure_installed = {
        "ansible-language-server",
        "ansible-lint",
        "antlers-language-server",
        "black",
        "bash-language-server",
        "blade-formatter",
        "docker-compose-language-service",
        "dockerfile-language-server",
        "dot-language-server",
        "emmet-ls",
        "eslint_d",
        "flake8",
        "hadolint",
        "html-lsp",
        "intelephense",
        "nginx-language-server",
        "php-debug-adapter",
        "phpstan",
        "pint",
        "prettierd",
        "pyright",
        "rustywind",
        "shellcheck",
        "shfmt",
        "stylua",
        "css-lsp",
        "css-variables-language-server",
        "css-variables-language-server",
      },
    },
  },
}
